use_default_settings:
  engines:
    keep_only:
      - bing
      - duckduckgo
      - startpage

general:
  instance_name: Job Search local metasearch
  debug: false

search:
  safe_search: 1
  formats:
    - html
    - json

server:
  limiter: false
  public_instance: false
  image_proxy: false

engines:
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: startpage
    disabled: false

ui:
  static_use_hash: true
