#!/usr/bin/env python3
"""Expose a host loopback HTTP proxy to Compose via a Unix socket.

On Linux, Docker bridge containers often cannot open TCP to the host gateway
(host.docker.internal / bridge IP), while a bind-mounted Unix socket works.
When services/hh/.env (or JOB_SEARCH_HOST_HTTP_PROXY) points at a loopback
HTTP proxy, this helper:

1. listens on ``.local/hh-host-http-proxy.sock``;
2. relays bytes to the host HTTP proxy (HTTP CONNECT);
3. writes ``.local/docker-compose.hh-egress.yml`` so Compose can attach
   ``hh-egress`` and rewrite container ``HTTP(S)_PROXY`` to that service.

Usage (via Makefile)::

    python3 scripts/host_http_proxy_socket.py ensure
    python3 scripts/host_http_proxy_socket.py compose-files   # prints -f args
    python3 scripts/host_http_proxy_socket.py stop
"""

from __future__ import annotations

import argparse
import os
import select
import signal
import socket
import sys
import threading
import time
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
LOCAL_DIR = ROOT / ".local"
DEFAULT_SOCKET = LOCAL_DIR / "hh-host-http-proxy.sock"
PID_FILE = LOCAL_DIR / "hh-host-http-proxy.pid"
OVERRIDE_FILE = LOCAL_DIR / "docker-compose.hh-egress.yml"
HH_ENV_FILE = ROOT / "services" / "hh" / ".env"

EGRESS_SERVICE = "hh-egress"
EGRESS_PORT = 3128
INTERNAL_PROXY_URL = f"http://{EGRESS_SERVICE}:{EGRESS_PORT}"

OVERRIDE_TEMPLATE = f"""# Generated by scripts/host_http_proxy_socket.py — do not commit.
services:
  {EGRESS_SERVICE}:
    image: alpine/socat:latest
    restart: unless-stopped
    command:
      - TCP-LISTEN:{EGRESS_PORT},bind=0.0.0.0,fork,reuseaddr
      - UNIX-CONNECT:/proxy.sock
    volumes:
      - ./.local/hh-host-http-proxy.sock:/proxy.sock

  hh:
    environment:
      HTTP_PROXY: {INTERNAL_PROXY_URL}
      HTTPS_PROXY: {INTERNAL_PROXY_URL}
      http_proxy: {INTERNAL_PROXY_URL}
      https_proxy: {INTERNAL_PROXY_URL}
      HH_PROXY: {INTERNAL_PROXY_URL}
      NO_PROXY: "127.0.0.1,localhost,hh,core,web,osint,postgres,searxng,{EGRESS_SERVICE}"
      no_proxy: "127.0.0.1,localhost,hh,core,web,osint,postgres,searxng,{EGRESS_SERVICE}"
    depends_on:
      {EGRESS_SERVICE}:
        condition: service_started
"""


def _read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def resolve_host_proxy_url() -> str | None:
    """Return the operator HTTP proxy URL used on the host, if any."""
    for key in (
        "JOB_SEARCH_HOST_HTTP_PROXY",
        "HTTPS_PROXY",
        "HTTP_PROXY",
        "https_proxy",
        "http_proxy",
        "HH_PROXY",
    ):
        value = os.environ.get(key, "").strip()
        if value:
            return value
    hh_env = _read_env_file(HH_ENV_FILE)
    for key in ("JOB_SEARCH_HOST_HTTP_PROXY", "HTTPS_PROXY", "HTTP_PROXY", "https_proxy", "http_proxy", "HH_PROXY"):
        value = hh_env.get(key, "").strip()
        if value:
            return value
    return None


def classify_proxy(url: str | None) -> str:
    """Return ``none``, ``loopback``, or ``remote``."""
    if not url:
        return "none"
    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"}:
        # Refuse undocumented schemes here; operator must use an HTTP proxy URL.
        return "none"
    host = (parsed.hostname or "").lower()
    if host in {"127.0.0.1", "localhost", "::1"}:
        return "loopback"
    return "remote"


def _relay(left: socket.socket, right: socket.socket) -> None:
    sockets = [left, right]
    try:
        while True:
            readable, _, errored = select.select(sockets, [], sockets, 60.0)
            if errored or not readable:
                break
            for src in readable:
                dst = right if src is left else left
                data = src.recv(65536)
                if not data:
                    return
                dst.sendall(data)
    except OSError:
        return
    finally:
        for sock in sockets:
            try:
                sock.shutdown(socket.SHUT_RDWR)
            except OSError:
                pass
            try:
                sock.close()
            except OSError:
                pass


def _accept_loop(server: socket.socket, target_host: str, target_port: int) -> None:
    while True:
        try:
            client, _ = server.accept()
        except OSError:
            break
        try:
            upstream = socket.create_connection((target_host, target_port), timeout=5.0)
        except OSError:
            client.close()
            continue
        thread = threading.Thread(target=_relay, args=(client, upstream), daemon=True)
        thread.start()


def _pid_running(pid: int) -> bool:
    if pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def _read_pid() -> int | None:
    if not PID_FILE.is_file():
        return None
    try:
        return int(PID_FILE.read_text(encoding="utf-8").strip())
    except ValueError:
        return None


def stop_forwarder() -> None:
    pid = _read_pid()
    if pid and _pid_running(pid):
        try:
            os.kill(pid, signal.SIGTERM)
        except OSError:
            pass
        for _ in range(20):
            if not _pid_running(pid):
                break
            time.sleep(0.05)
    if PID_FILE.exists():
        PID_FILE.unlink(missing_ok=True)
    if DEFAULT_SOCKET.exists():
        try:
            DEFAULT_SOCKET.unlink()
        except OSError:
            pass
    if OVERRIDE_FILE.exists():
        OVERRIDE_FILE.unlink(missing_ok=True)


def _write_override_loopback() -> None:
    LOCAL_DIR.mkdir(parents=True, exist_ok=True)
    # Keep path relative for Compose on any machine; socket name is fixed.
    OVERRIDE_FILE.write_text(OVERRIDE_TEMPLATE, encoding="utf-8")


def _write_override_remote(proxy_url: str) -> None:
    LOCAL_DIR.mkdir(parents=True, exist_ok=True)
    text = f"""# Generated by scripts/host_http_proxy_socket.py — do not commit.
services:
  hh:
    environment:
      HTTP_PROXY: {proxy_url}
      HTTPS_PROXY: {proxy_url}
      http_proxy: {proxy_url}
      https_proxy: {proxy_url}
      HH_PROXY: {proxy_url}
"""
    OVERRIDE_FILE.write_text(text, encoding="utf-8")


def start_forwarder(proxy_url: str) -> None:
    parsed = urlparse(proxy_url)
    host = parsed.hostname or "127.0.0.1"
    port = parsed.port or (443 if parsed.scheme == "https" else 80)

    existing = _read_pid()
    if existing and _pid_running(existing) and DEFAULT_SOCKET.exists():
        _write_override_loopback()
        return

    stop_forwarder()
    LOCAL_DIR.mkdir(parents=True, exist_ok=True)
    if DEFAULT_SOCKET.exists():
        DEFAULT_SOCKET.unlink()

    server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    server.bind(str(DEFAULT_SOCKET))
    os.chmod(DEFAULT_SOCKET, 0o666)
    server.listen(64)

    # Double-fork daemon so Makefile callers return immediately.
    if os.fork() > 0:
        time.sleep(0.1)
        if not DEFAULT_SOCKET.exists():
            raise RuntimeError("host HTTP proxy socket failed to start")
        _write_override_loopback()
        return

    os.setsid()
    if os.fork() > 0:
        os._exit(0)

    PID_FILE.write_text(str(os.getpid()), encoding="utf-8")
    _write_override_loopback()
    try:
        _accept_loop(server, host, port)
    finally:
        server.close()
        if PID_FILE.exists() and _read_pid() == os.getpid():
            PID_FILE.unlink(missing_ok=True)
        if DEFAULT_SOCKET.exists():
            DEFAULT_SOCKET.unlink(missing_ok=True)
        os._exit(0)


def ensure() -> int:
    mode = os.environ.get("JOB_SEARCH_HH_HOST_PROXY_MODE", "auto").strip().lower()
    proxy_url = resolve_host_proxy_url()
    kind = classify_proxy(proxy_url) if mode == "auto" else mode

    if mode == "off" or kind in {"none", "off"}:
        stop_forwarder()
        print("hh-host-proxy: disabled", file=sys.stderr)
        return 0

    if mode == "remote" or kind == "remote":
        assert proxy_url is not None
        stop_forwarder()
        _write_override_remote(proxy_url)
        print(f"hh-host-proxy: remote override → {urlparse(proxy_url).hostname}", file=sys.stderr)
        return 0

    # loopback (auto or forced)
    if not proxy_url or classify_proxy(proxy_url) != "loopback":
        # Forced loopback without URL — fail clearly.
        if mode == "loopback":
            print("hh-host-proxy: loopback mode requires JOB_SEARCH_HOST_HTTP_PROXY or HH HTTP_PROXY", file=sys.stderr)
            return 1
        stop_forwarder()
        print("hh-host-proxy: disabled (no loopback HTTP proxy configured)", file=sys.stderr)
        return 0

    start_forwarder(proxy_url)
    parsed = urlparse(proxy_url)
    print(
        f"hh-host-proxy: loopback socket → {parsed.hostname}:{parsed.port or 80} "
        f"(Compose override {OVERRIDE_FILE.name})",
        file=sys.stderr,
    )
    return 0


def compose_files() -> int:
    """Print extra ``docker compose -f`` arguments when an override exists."""
    print("-f")
    print(str(ROOT / "compose.yaml"))
    if OVERRIDE_FILE.is_file():
        print("-f")
        print(str(OVERRIDE_FILE))
    return 0


def detect() -> int:
    kind = classify_proxy(resolve_host_proxy_url())
    print(kind)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("ensure", "stop", "detect", "compose-files"))
    args = parser.parse_args(argv)
    if args.command == "ensure":
        return ensure()
    if args.command == "stop":
        stop_forwarder()
        print("hh-host-proxy: stopped", file=sys.stderr)
        return 0
    if args.command == "detect":
        return detect()
    return compose_files()


if __name__ == "__main__":
    raise SystemExit(main())
