#!/usr/bin/env python3
"""Expose host-loopback Ollama to Compose via a Unix socket (Linux bridge gap).

Compose bridge containers on this host cannot open TCP to host.docker.internal
(gateway timeouts). Mirror the HH egress pattern:

1. listen on ``.local/ollama-host.sock``;
2. relay accepted connections to ``127.0.0.1:11434``;
3. write ``.local/docker-compose.ollama-egress.yml`` so Scoring uses
   ``http://ollama-egress:11434``.

Usage (via Makefile)::

    python3 scripts/ollama_host_socket.py ensure
    python3 scripts/ollama_host_socket.py compose-files
    python3 scripts/ollama_host_socket.py stop
"""

from __future__ import annotations

import argparse
import os
import select
import signal
import socket
import sys
import threading
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCAL_DIR = ROOT / ".local"
DEFAULT_SOCKET = LOCAL_DIR / "ollama-host.sock"
PID_FILE = LOCAL_DIR / "ollama-host.pid"
OVERRIDE_FILE = LOCAL_DIR / "docker-compose.ollama-egress.yml"

EGRESS_SERVICE = "ollama-egress"
EGRESS_PORT = 11434
HOST_OLLAMA = ("127.0.0.1", 11434)
INTERNAL_OLLAMA_URL = f"http://{EGRESS_SERVICE}:{EGRESS_PORT}"

OVERRIDE_TEMPLATE = f"""# Generated by scripts/ollama_host_socket.py — do not commit.
services:
  {EGRESS_SERVICE}:
    image: alpine/socat:latest
    restart: unless-stopped
    command:
      - TCP-LISTEN:{EGRESS_PORT},bind=0.0.0.0,fork,reuseaddr
      - UNIX-CONNECT:/ollama.sock
    volumes:
      - ./.local/ollama-host.sock:/ollama.sock

  scoring:
    environment:
      JOB_SEARCH_SCORING_OLLAMA_BASE_URL: {INTERNAL_OLLAMA_URL}
    depends_on:
      {EGRESS_SERVICE}:
        condition: service_started

  scoring-worker:
    environment:
      JOB_SEARCH_SCORING_OLLAMA_BASE_URL: {INTERNAL_OLLAMA_URL}
    depends_on:
      {EGRESS_SERVICE}:
        condition: service_started
"""


def _relay(client: socket.socket, upstream: socket.socket) -> None:
    sockets = [client, upstream]
    try:
        while True:
            readable, _, errored = select.select(sockets, [], sockets, 60.0)
            if errored or not readable:
                break
            for source in readable:
                target = upstream if source is client else client
                data = source.recv(65536)
                if not data:
                    return
                target.sendall(data)
    except OSError:
        return
    finally:
        for sock in sockets:
            try:
                sock.shutdown(socket.SHUT_RDWR)
            except OSError:
                pass
            try:
                sock.close()
            except OSError:
                pass


def _accept_loop(server: socket.socket) -> None:
    while True:
        try:
            client, _ = server.accept()
        except OSError:
            return
        try:
            upstream = socket.create_connection(HOST_OLLAMA, timeout=5)
        except OSError:
            client.close()
            continue
        threading.Thread(target=_relay, args=(client, upstream), daemon=True).start()


def _write_override() -> None:
    LOCAL_DIR.mkdir(parents=True, exist_ok=True)
    OVERRIDE_FILE.write_text(OVERRIDE_TEMPLATE, encoding="utf-8")


def _pid_running(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def ensure() -> int:
    """Start host→Ollama socket relay and write Compose override."""
    LOCAL_DIR.mkdir(parents=True, exist_ok=True)
    try:
        probe = socket.create_connection(HOST_OLLAMA, timeout=2)
        probe.close()
    except OSError as error:
        print(f"ollama-host: cannot reach {HOST_OLLAMA[0]}:{HOST_OLLAMA[1]} ({error})", file=sys.stderr)
        return 1

    if PID_FILE.is_file():
        try:
            old_pid = int(PID_FILE.read_text(encoding="utf-8").strip())
        except ValueError:
            old_pid = 0
        if old_pid and _pid_running(old_pid):
            _write_override()
            print(f"ollama-host: already running pid={old_pid}")
            return 0

    if DEFAULT_SOCKET.exists():
        DEFAULT_SOCKET.unlink()

    server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    server.bind(str(DEFAULT_SOCKET))
    server.listen(128)
    DEFAULT_SOCKET.chmod(0o666)

    pid = os.fork()
    if pid > 0:
        PID_FILE.write_text(str(pid), encoding="utf-8")
        _write_override()
        print(f"ollama-host: socket → {HOST_OLLAMA[0]}:{HOST_OLLAMA[1]} (override {OVERRIDE_FILE.name})")
        return 0

    # Child
    os.setsid()
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))
    _accept_loop(server)
    return 0


def stop() -> int:
    """Stop host socket relay and remove override file."""
    if PID_FILE.is_file():
        try:
            pid = int(PID_FILE.read_text(encoding="utf-8").strip())
        except ValueError:
            pid = 0
        if pid:
            try:
                os.kill(pid, signal.SIGTERM)
                for _ in range(20):
                    if not _pid_running(pid):
                        break
                    time.sleep(0.05)
            except OSError:
                pass
        PID_FILE.unlink(missing_ok=True)
    if DEFAULT_SOCKET.exists():
        DEFAULT_SOCKET.unlink()
    OVERRIDE_FILE.unlink(missing_ok=True)
    print("ollama-host: stopped")
    return 0


def compose_files() -> int:
    """Print override path when present (for Makefile COMPOSE aggregation)."""
    if OVERRIDE_FILE.is_file():
        print(OVERRIDE_FILE)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("ensure", "stop", "compose-files"))
    args = parser.parse_args()
    if args.command == "ensure":
        return ensure()
    if args.command == "stop":
        return stop()
    return compose_files()


if __name__ == "__main__":
    raise SystemExit(main())
